import styles from "../styles/Home.module.css";
import { loadFoods } from "../lib/load-foods";

import React, { useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import FoodCard from "../components/FoodCard";
import { Food } from "../types/foodType";

export const getServerSideProps: GetServerSideProps = async () => {
  const foodData = await loadFoods();

  return {
    props: {
      foodData,
    },
  };
};

const Home: NextPage<{ foodData: Food[] }> = ({ foodData }) => {
  const [userQuery, setUserQuery] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="text"
          value={userQuery}
          onChange={(e) => setUserQuery(e.target.value)}
        />
        <div className={styles.section}>
          {foodData
            .filter((food) =>
              food.name.toLowerCase().includes(userQuery.toLowerCase())
            )
            .map((food) => {
              return <FoodCard food={food} key={food.id} />;
            })}
        </div>
      </main>
    </div>
  );
};

export default Home;
