import styles from "../styles/Home.module.css";

import React, { useMemo, useState } from "react";
import { NextPage } from "next";
import Head from "next/head";
import FoodList from "../data/foods.json";
import FoodCard from "../components/FoodCard";

const Home: NextPage = () => {
  const [userQuery, setUserQuery] = useState("");
  const [toggleSortButton, setToggleSortButton] = useState(true);

  const renderedFood = useMemo(() => {
    const searchResults = [...FoodList].filter((FoodItem) =>
      FoodItem.name.toLowerCase().includes(userQuery.toLowerCase())
    );
    const sortedResults = searchResults.sort((FoodItemA, FoodItemB) => {
      if (toggleSortButton) {
        return FoodItemB.rating - FoodItemA.rating;
      } else {
        return FoodItemA.rating - FoodItemB.rating;
      }
    });
    return sortedResults;
  }, [userQuery, toggleSortButton]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          type="button"
          onClick={() => setToggleSortButton(!toggleSortButton)}
        >
          Rating {toggleSortButton ? "↓" : "↑"}
        </button>
        <input
          type="text"
          value={userQuery}
          onChange={(e) => setUserQuery(e.target.value)}
          placeholder="Search food here..."
        />
        <div className={styles.section}>
          {renderedFood.map((foodItem) => (
            <FoodCard key={foodItem.id} food={foodItem} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
